### ISSUE TITLE
Form Helper Label

### ISSUE THREAD

**Issue by vladshcherbin** [jagi/meteor-astronomy-examples#1]
For forms, I would like to make a helper, e.g. inputElement, so I can use it like this:

``` js
{{> input field='firstName'}}
```

``` html
  <div>
    <label for="firstName">First name {{HERE}}</label>
    <input id="firstName" type="text" value="{{firstName}}" class="{{#if hasError 'firstName'}}error{{/if}}" />
  </div>
  {{#if hasError 'firstName'}}
    <div class="error">{{getError 'firstName'}}</div>
  {{/if}}
```

Inside, I would like to have a Label (instead of First name), taken from the object. So, that I don't need to pass it to create input, edit input. How can this be done?

**Comment by lukejagodzinski** [comment]
The feature you are writing about is related to `forms` module which is in plans. I have some ideas on how to implement such module but right now is to early to discuss that. However I will open discussion when I'm ready to start working on that. Any ideas will be appreciated.

**Comment by vladshcherbin** [comment]
@jagi sure, thank you. I will be now using astronomy, but forms is a miss now. I will share any thoughts I might have during the use. Hope, you will finish astronomy so that we can somehow make forms ;)
