### ISSUE TITLE
Flowrouter integration

### ISSUE THREAD

**Issue by frankapimenta** [jagi/meteor-astronomy-examples#11]
I was trying to integrate this example in one of my project features but I use flow-router with template level subscriptions.
I could not put it to work  because I can't get the object data in the events method save.
Moreover with the reactivevar (curValue) i cannot access getValidationErrors et. al..somehow they do not come with the submit.

Is there any issues with Flowrouter when working with this? Any reference I could check besides the flowrouter wiki?

Thank you in advance

**Comment by lukejagodzinski** [comment]
Have you checked the `flowrouter` branch of this repository?

**Comment by frankapimenta** [comment]
Oh sorry

Didn't checked for
It but I will.

Thank you

No dia 31.10.2015, às 12:15, jagi notifications@github.com escreveu:

**Comment by lukejagodzinski** [comment]
No problem :)

**Comment by frankapimenta** [comment]
missing .get in {{#with user}}...it happens :dash:

working :dancer: 

thanks

**Comment by lukejagodzinski** [comment]
Good to hear :)
