### ISSUE TITLE
Submit button does not work

### ISSUE THREAD

**Issue by james1293** [jagi/meteor-astronomy-examples#15]
Steps to reproduce: 

1. `git clone https://github.com/jagi/meteor-astronomy-examples.git`
2. `cd meteor-astronomy-examples`
3. `meteor npm install`
4. `meteor`
5. In the UI, press the + button
6. fill out form with valid data (no phone numbers)
7. press submit
8. nothing happens.

Let me know what other details I should provide, thanks!.

**Comment by lukejagodzinski** [comment]
Yep, you're right. Sorry for that. At some point, when making test I've accidentally committed not working code. I've fixed it. You can check it out. Thanks for letting know about that bug!

**Comment by james1293** [comment]
Thanks for the quick fix!
