### ISSUE TITLE
valueAsDate not supported in Firefox?

### ISSUE THREAD

**Issue by james1293** [jagi/meteor-astronomy-examples#16]
It seems that valueAsDate is not supported in Firefox (evidence [here](http://stackoverflow.com/questions/30503195/html-5-input-type-date-not-working-in-firefox) and [here](http://html5test.com) ). Therefore, in Firefox, the program will always think that the birth date is wrong.

Do you think this is a strong enough reason to switch to another way of converting the date input to a Date() object? I'm concerned that people will try this example in Firefox, and decide that Astronomy is broken when they try to submit the form and it does not work.

Let me know what you think, thanks!

**Comment by lukejagodzinski** [comment]
Yes I know about that limitation of FF. I don't know why I actually used `valueAsDate` here. It would work without that. That's why we have casting system in Astronomy. I will remove it and check if it's working. Thanks for reminding me about that!

**Comment by lukejagodzinski** [comment]
Ok I've made a few more fixes and now it should work properly
