### ISSUE TITLE
   error: No compatible binary build found for this package. 

### ISSUE THREAD

**Issue by parhelium** [jagi/meteor-astronomy-examples#2]
=> Errors prevented startup:                  

   While checking for jagi:astronomy-validators@0.8.3:
   error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

**Comment by parhelium** [comment]
Oh, this one issue is serious as it blocks my development process... 
Fortunately I can run my app, but cannot run `meteor update`.

**Comment by lukejagodzinski** [comment]
Hmm it seems to be problem with Atmosphere. When I was publishing package there was an error. However on the Atmosphere it was noted that version have been correctly published. I will just update version number in the 30 min. Stay tuned.

**Comment by parhelium** [comment]
Thanks for quick response ! Will check in 30 minutes.

**Comment by parhelium** [comment]
I'm glad everything is on github.
I fixed this problem by cloning your repos and creating symlinks to `packages` dir in my project.
Of course it has some disadvantages as need for manual `pull` in case of any update, but in the same time I have more control. Once `atmosphere` will be fixed, then I will try to test `jagi*` packages from atmosphere.

**Comment by lukejagodzinski** [comment]
@parhelium sorry for a delay I had other work to do. But I've updated Validators to version 0.8.4 and it should work correctly now. I will also post an issue on the Meteor repo because it's not the first time I had this problem.

**Comment by parhelium** [comment]
@jagi  Thanks ! I confirm your update has fixed issue.

**Comment by lukejagodzinski** [comment]
Thanks :)
