### ISSUE TITLE
Misleading name of the variable

### ISSUE THREAD

**Issue by darko-mijic** [jagi/meteor-astronomy-examples#6]
I think that the name of the variable **user** is misleading for understanding this example. 

``` javascript
Template.Form.events({
  'change input': function(e, tmpl) {
    var user = this;

    var field = e.currentTarget;
    user.set(field.id, field.value);
    user.validate(field.id);
  }
});
```

Variable user is mapped to current data context of the template instance. So it is assigned to User, Address or Phone Astro class since this example is handling **change input** event on Form template level so it is handling that event for nested templates AddressForm and PhoneForm also which have different data context.

**Comment by lukejagodzinski** [comment]
Oh right, thanks for noticing it. I haven't changed it after releasing 1.0.0 where I've introduced new way of nesting documents.

**Comment by lukejagodzinski** [comment]
Ok I've change it to `doc` as it can be top level or nested document.
